output "cluster_id" {
  description = "EKS cluster ID"
  value       = aws_eks_cluster.toot-eks.id
}

output "cluster_endpoint" {
  description = "Endpoint for EKS control plane"
  value       = aws_eks_cluster.toot-eks.endpoint
}


output "kubectl_config" {
  description = "kubectl config as generated by the AWS CLI"
  value       = "aws eks update-kubeconfig --name ${aws_eks_cluster.toot-eks.name} --region ${var.region}"
}

output "current_aws_user" {
  description = "Current aws user arn"
  value       = data.aws_caller_identity.current.arn
}
