apiVersion: external-secrets.io/v1alpha1
kind: SecretStore
metadata:
  name: aws-secrets
  namespace: argocd
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-west-2
      auth:
        secretRef:
          accessKeyIDSecretRef:
            name: aws-login
            namespace: external-secrets
            key: access-key
          secretAccessKeySecretRef:
            name: aws-login
            namespace: external-secrets
            key: secret-access-key