apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: fetcher-from-aws
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets
    kind: SecretStore
  target:
    name: toot-deploy-secret
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: argocd-git-repo-key-2
