apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: example
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets
    kind: ClusterSecretStore
  target:
    name: toot-deploy-secret
    namespace: argocd
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: argocd-git-repo-key-1
