name: Config automation tools

on:
  workflow_dispatch:
    inputs:
        cluster:
          description: 'EKS cluster name'
          required: true
          default: 'k8-toot'
          type: string

env:
  AWS_REGION: us-west-2
  TF_VAR_github_env: "true"

jobs:
  aws-infraatructure:
    name: ${{github.run_number}} - Configure automation tools
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
      - name: Install kubectl
        uses: azure/setup-kubectl@v4
      - name: Config kubectl to connect cluster
        run: |
          aws eks update-kubeconfig \
            --region ${{ env.AWS_REGION }} \
            --name ${{ github.event.inputs.cluster }}

      - name: Create secret of aws credentials
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          kubectl create secret generic aws-login \
            --from-literal "access-key=${AWS_ACCESS_KEY_ID}" \
            --from-literal "secret-access-key=${AWS_SECRET_ACCESS_KEY}" --namespace argocd \
            --dry-run=client -o yaml > /tmp/aws-login.yaml
          sed -i 's/namespace: argocd/namespace: mastodon/' /tmp/aws-login.yaml
          kubectl create namespace mastodon || true
          kubectl apply -f /tmp/aws-login.yaml
          rm /tmp/aws-login.yaml
      - name: Create secret store for argocd
        run: kubectl apply -f ./etc/secretStore.yaml
      - name: Create external repo in argocd
        run: kubectl apply -f etc/secret-argocd-repo.yaml
      - name: Create toot application
        run: kubectl apply -f etc/mastodon-app.yaml
